# Generated by Django 2.1.3 on 2018-11-30 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome do Produto')),
                ('slug', models.SlugField(unique=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço do produto')),
                ('datePost', models.DateField(auto_now_add=True)),
                ('tipyDept', models.CharField(max_length=20, verbose_name='Departamento')),
                ('description', models.TextField(verbose_name='Descrição do produto')),
                ('juros', models.BooleanField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/images', verbose_name='Imagem do Produto')),
                ('maxParc', models.IntegerField(verbose_name='Total de Parcelas')),
                ('cpfUserPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['id'],
            },
        ),
    ]
