# Generated by Django 2.1.3 on 2018-11-20 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0007_auto_20181102_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome do Produto')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço do produto')),
                ('datePost', models.DateField(verbose_name='Postado em')),
                ('tipyDept', models.CharField(max_length=20, verbose_name='Departamento')),
                ('description', models.TextField(verbose_name='Descrição do produto')),
                ('juros', models.BooleanField()),
                ('image', models.ImageField(upload_to='product/images', verbose_name='Imagem do Produto')),
                ('maxParc', models.IntegerField(verbose_name='Total de Parcelas')),
                ('cpfUserPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['id'],
            },
        ),
    ]
