# Generated by Django 2.1.3 on 2018-12-05 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=200, verbose_name='Comentário do produto')),
                ('nota', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Nota')),
                ('title', models.TextField(max_length=50, verbose_name='Titulo do comentario')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['nota'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='littleDescription',
            field=models.TextField(default=1, verbose_name='Curta descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coment',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
