# Generated by Django 2.1.2 on 2018-11-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datePost',
            field=models.DateField(auto_now_add=True),
        ),
    ]
