# Generated by Django 2.1.3 on 2018-12-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20181205_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Descrição do produto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='littleDescription',
            field=models.TextField(max_length=50, verbose_name='Curta descrição'),
        ),
    ]
