# Generated by Django 2.1.2 on 2018-11-27 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20181123_1023'),
        ('product', '0003_auto_20181122_1425'),
    ]

    operations = [
    ]
