# Generated by Django 2.1.2 on 2018-10-27 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome do Produto')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço do produto')),
                ('datePost', models.DateField(verbose_name='Postado em:')),
                ('tipyDept', models.CharField(max_length=20, verbose_name='Departamento')),
                ('description', models.TextField(verbose_name='Descrição do produto')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='Nome do usuario')),
                ('password', models.CharField(max_length=15, verbose_name='senha')),
                ('cpf', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='CPF usuario')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='cpfUserPost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
