# Generated by Django 2.1.2 on 2018-11-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181101_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='juros',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
