# Generated by Django 2.1.2 on 2018-11-01 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_product_juros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='juros',
        ),
    ]
