# Generated by Django 2.1.2 on 2018-11-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_product_juros'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='juros',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
