# Generated by Django 2.1.3 on 2018-11-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20181128_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='CPF usuario'),
        ),
    ]
