# Generated by Django 2.1.3 on 2018-12-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20181130_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutosComprados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(verbose_name='nome do produto')),
                ('data_compra', models.DateTimeField(verbose_name='Data de compra')),
            ],
        ),
    ]
